# Generated by Django 4.0.3 on 2022-04-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_project_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contributor',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'AUTHOR')), fields=('project',), name='unique_author_per_project'),
        ),
    ]
