# Generated by Django 4.0.3 on 2022-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_contributor_unique_author_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Auteur'), ('CONTRIBUTOR', 'Collaborateur')], default='CONTRIBUTOR', max_length=11),
        ),
    ]
