# Generated by Django 4.0.3 on 2022-05-01 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0005_alter_contributor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', through='projects.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
