# Generated by Django 4.0.3 on 2022-05-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
